/* SPDX-License-Identifier: GPL-3.0-or-later */
#define _GNU_SOURCE
#include "config.h"
#include <ctype.h>
#include <errno.h>
#include <getopt.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

bool config_parse_count(const char *text, uint64_t minimum, uint64_t maximum, uint64_t *value)
{
    if (!text || !*text || !value || minimum > maximum)
        return false;
    for (const char *p = text; *p; ++p)
        if (!isdigit((unsigned char)*p))
            return false;
    errno = 0;
    unsigned long long number = strtoull(text, NULL, 10);
    if (errno || number < minimum || number > maximum)
        return false;
    *value = number;
    return true;
}

bool config_parse_bytes(const char *text, uint64_t *value)
{
    if (!text || !value || !isdigit((unsigned char)*text))
        return false;
    char *suffix;
    errno = 0;
    uint64_t number = strtoull(text, &suffix, 10), multiplier = 1;
    if (errno || !number)
        return false;
    const char *units[] = {"", "B", "K", "KB", "KiB", "M", "MB", "MiB", "G", "GB", "GiB"};
    size_t i;
    for (i = 0; i < sizeof(units) / sizeof(*units); ++i)
        if (!strcasecmp(suffix, units[i]))
            break;
    if (i == sizeof(units) / sizeof(*units))
        return false;
    if (i >= 2)
        multiplier = 1ULL << (10 * (1 + (i - 2) / 3));
    if (number > UINT64_MAX / multiplier)
        return false;
    *value = number * multiplier;
    return true;
}

bool config_parse_cpu(const char *text, struct cpu_limit *value)
{
    if (!text || !value)
        return false;
    const char *slash = strchr(text, '/');
    char quota[32];
    if (!slash || (size_t)(slash - text) >= sizeof(quota))
        return false;
    memcpy(quota, text, (size_t)(slash - text));
    quota[slash - text] = '\0';
    struct cpu_limit parsed;
    if (!config_parse_count(quota, 1000, UINT64_MAX, &parsed.quota) ||
        !config_parse_count(slash + 1, 1000, 1000000, &parsed.period))
        return false;
    *value = parsed;
    return true;
}

bool config_valid_hostname(const char *name)
{
    if (!name || !*name || strlen(name) > 64)
        return false;
    if (!isalnum((unsigned char)*name) || !isalnum((unsigned char)name[strlen(name) - 1]))
        return false;
    for (const char *p = name; *p; ++p)
        if ((!isalnum((unsigned char)*p) && *p != '-' && *p != '.') ||
            (*p == '.' && p[1] == '.'))
            return false;
    return true;
}

void config_init(struct container_config *config)
{
    *config = (struct container_config){.memory_bytes = CONTAINED_DEFAULT_MEMORY,
                                        .cpu = {CONTAINED_DEFAULT_CPU_QUOTA, CONTAINED_DEFAULT_CPU_PERIOD},
                                        .pids = CONTAINED_DEFAULT_PIDS,
                                        .nofile = CONTAINED_DEFAULT_NOFILE,
                                        .cgroup_parent = CONTAINED_DEFAULT_CGROUP_PARENT};
}

void config_print_usage(FILE *stream, const char *program)
{
    fprintf(stream, "Usage: %s --rootfs PATH [OPTIONS] -- COMMAND [ARG...]\n"
                    "  -r, --rootfs PATH          Dedicated root filesystem (required)\n"
                    "  -m, --memory SIZE          Memory ceiling (default 256M; K/M/G/KiB/MiB/GiB)\n"
                    "  -c, --cpu QUOTA/PERIOD     CPU microseconds (default 50000/100000)\n"
                    "  -p, --pids COUNT           Process ceiling (default 64)\n"
                    "  -f, --nofile COUNT         Descriptor ceiling (default 256)\n"
                    "  -H, --hostname NAME        Hostname (generated by default)\n"
                    "  -C, --cgroup-parent PATH   Delegated parent (default /sys/fs/cgroup)\n"
                    "      --writable-rootfs      Allow writes to supplied rootfs\n"
                    "  -h, --help                 Show help\n",
            program);
}

enum config_parse_result config_parse(struct container_config *config, int argc, char **argv, FILE *errors)
{
    static const struct option options[] = {
        {"rootfs", 1, NULL, 'r'}, {"memory", 1, NULL, 'm'}, {"cpu", 1, NULL, 'c'}, {"pids", 1, NULL, 'p'}, {"nofile", 1, NULL, 'f'}, {"hostname", 1, NULL, 'H'}, {"cgroup-parent", 1, NULL, 'C'}, {"writable-rootfs", 0, NULL, 'w'}, {"help", 0, NULL, 'h'}, {NULL, 0, NULL, 0}};
    config_init(config);
    opterr = 0;
    int option;
    const char *error = NULL;
    while ((option = getopt_long(argc, argv, "+r:m:c:p:f:H:C:hw", options, NULL)) != -1)
    {
        switch (option)
        {
        case 'r':
            config->rootfs = optarg;
            break;
        case 'C':
            config->cgroup_parent = optarg;
            if (!*optarg)
                error = "cgroup parent must not be empty";
            break;
        case 'w':
            config->writable_rootfs = true;
            break;
        case 'h':
            return CONFIG_PARSE_HELP;
        case 'm':
            if (!config_parse_bytes(optarg, &config->memory_bytes))
                error = "invalid memory limit";
            break;
        case 'c':
            if (!config_parse_cpu(optarg, &config->cpu))
                error = "invalid CPU limit";
            break;
        case 'p':
            if (!config_parse_count(optarg, 1, 1048576, &config->pids))
                error = "invalid PID limit";
            break;
        case 'f':
            if (!config_parse_count(optarg, 3, 1048576, &config->nofile))
                error = "invalid file-descriptor limit";
            break;
        case 'H':
            config->hostname = optarg;
            if (!config_valid_hostname(optarg))
                error = "invalid hostname";
            break;
        default:
            error = "unknown or incomplete option";
            break;
        }
        if (error)
            break;
    }
    if (!error && (!config->rootfs || !*config->rootfs))
        error = "--rootfs is required";
    if (!error && optind >= argc)
        error = "a command is required after --";
    if (error)
    {
        fprintf(errors, "contained: %s\n", error);
        return CONFIG_PARSE_ERROR;
    }
    config->command = &argv[optind];
    return CONFIG_PARSE_OK;
}
